---
- hosts: etc
  remote_user: anserv
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Reemplazar linea zabbix en /etc/zabbix
    command: sed 's/Server=Server=127.0.0.1,192.168.1.113/'Server=192.168.1.113,192.168.100.83'/g' -i /etc/zabbix/zabbix_agentd.conf
    register: result