---
- hosts: 192.168.100.100, 192.168.100.102
  remote_user: anserv
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Instalar agente zabbix
    apt: 
      name: zabbix-agent
      state: present    
