---
- hosts: Debian, Ubuntu
  remote_user: anserv
  #become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Hacer locate para archivo zabbix
    command: locate zabbix_agentd.conf
    register: result
