---
- hosts: all
  remote_user: anserv
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - debug: var=hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['ansible_hostname']~
