---
- hosts: ruta
  remote_user: anserv
  become: true
  become_method: sudo
  become_user: root

  tasks:
  
  - name: Ejecutar la ruta para zabbix
    shell: ip route add 172.26.251.0/24 via 192.168.151.1
  
  - name: Agregar ruta para zabbix en /etc/rc.local
    shell: echo "/sbin/ip route add 172.26.251.0/24 via 192.168.151.1" >> /etc/rc.local
