---
- hosts: 192.168.1.179

  tasks:
  - name:  Crear VM con modulo de Powershell
    win_command: powershell.exe -
    args: 
      stidn: Connect-CIServer -Server paneldcv.empresas.antel.com.uy -Org CEIBAL -User ansible -Password An5!bL3@execP14Ybook | 
      New-CIVApp -Name 'ansibletest' -OrgVdc 'VDC01-PAN01-E27024-CEIBAL-PROD1'
     
    register: stdout_lines  
