---
- hosts: 192.168.1.122
  remote_user: anserv
  become: true
  become_user: anserv
  become_method: sudo
  tasks:
  - name: Purgar la instalacion de agente zabbix y paquetes adyacentes
    register: result
    apt: 
     name: zabbix-agent
     state: absent
     purge: yes
  - name: Instalar agente nagios
    register: result
    apt: 
     name: nagios-nrpe-server
     state: present
     
